Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox"
  config.vm.provision :"shell", path: "installpuppet.sh"
  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "default.pp"
  end
end
